apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1 # number of copies
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend # Pod label
      annotations:
        co.elastic.logs/enabled: "true"
        co.elastic.logs/module: springboot
        co.elastic.logs/json.keys_under_root: "true"
        co.elastic.logs/json.add_error_key: "true"
    spec:
      containers:
        - name: backend
          image: nobugsme/nbank:with_username_error_fix
          imagePullPolicy: Always
          ports:
            - containerPort: 4111
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend # Service will route the traffic to pods with app=backend
  ports:
    - name: http
      protocol: TCP
      port: 4111 # service working port
      targetPort: 4111 # container listens this port
  type: NodePort # ClusterIP (only inside cluster), NodePort (opens port on all nodes of the cluster)
