name: Run tests

on:
  push:
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  run-tests:
    name: Set up services (review apps) and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up services
        run: cd infra/docker_compose && bash restart_docker.sh && cd ../..

      - name: Build project
        run: chmod +x ./mvnw && ./mvnw clean package -q

      - name: Run tests + Checkstyle
        run: ./mvnw verify -q
        env:
          APIBASEURL: http://localhost:4111
          UIBASEURL: http://nginx:80

      - name: Build Docker image
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          docker build -t myapp:${COMMIT_HASH} .
          echo "✅ Built image: myapp:${COMMIT_HASH}"
          
      - name: Push image to Docker Hub
        run: |
          chmod +x ./push-tests.sh
          ./push-tests.sh
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
