name: Run tests

# trigger
on: [ push, workflow_dispatch ]

jobs: # analogue of steps
  run-tests:
    name: Set up services (review apps) and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo # copy repo files into CI agent
        uses: action/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '23'

      - name: Cache Maven repo
        uses: actions:cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - name: Set up services
        run: bash infra/docker_compose/restart_docker.sh

      - name: Run tests
        run: ./mvnw clean test -q
          env:
            APIBASEURL: http://localhost:4111
            UIBASEURL: http://frontend