name: Run tests

on:
  push:
    paths: ['src/**']
  pull_request:
    paths: ['src/**']
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up services
        run: cd infra/docker_compose && bash restart_docker.sh && cd ../..

      - name: Verify (build+test+checkstyle)
        run: chmod +x ./mvnw && ./mvnw -q verify
        env:
          APIBASEURL: http://localhost:4111
          UIBASEURL: http://nginx:80

      - name: Run Swagger coverage
        if: always()
        run: |
          chmod +x ./.swagger-coverage-commandline/bin/swagger-coverage-commandline
          ./.swagger-coverage-commandline/bin/swagger-coverage-commandline \
            -s http://localhost:4111/v3/api-docs \
            -i target/swagger-coverage-output


      - name: Load test report history
        uses: actions/checkout@v2
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh-pages: gh-pages
          allure-results: target/allure-results
          allure_history: allure-history

      - name: Build Swagger coverage report
        if: always()
        run: sudo cp swagger-coverage-report.html allure-history/${{ github.run_number }}

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Build & push Docker image
        run: |
          chmod +x ./push-tests.sh
          DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} \
          DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }} \
          ./push-tests.sh

      - name: Clean up services
        if: always()
        run: cd infra/docker_compose && docker compose down
