name: Run tests

on:
  push:
    paths: ['src/**']
  pull_request:
    paths: ['src/**']
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up services
        run: cd infra/docker_compose && bash restart_docker.sh && cd ../..

      - name: Verify (build+test+checkstyle)
        run: chmod +x ./mvnw && ./mvnw -q verify
        env:
          APIBASEURL: http://localhost:4111
          UIBASEURL: http://nginx:80

      - name: Build & push Docker image
        run: |
          chmod +x ./push-tests.sh
          DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} \
          DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }} \
          ./push-tests.sh
